site_name: "Prelude: A sleek, modern, simple and powerful Emacs experience for everyone"
repo_url: https://github.com/bbatsov/prelude
copyright: "Copyright (C) 2011-2026 Bozhidar Batsov and Prelude contributors"
docs_dir: docs
nav:
- Home: index.md
- Installation: installation.md
- Usage: usage.md
- Configuration: configuration.md
- Modules:
    - Overview: modules/index.md
    - Foundation Modules:
        - Programming: modules/programming.md
        - Lisp Base: modules/lisp.md
        - LSP: modules/lsp.md
        - Company: modules/company.md
    - Programming Languages:
        - C/C++: modules/c.md
        - Clojure: modules/clojure.md
        - Common Lisp: modules/common_lisp.md
        - CSS: modules/css.md
        - Dart: modules/dart.md
        - Elixir: modules/elixir.md
        - Emacs Lisp: modules/emacs_lisp.md
        - Erlang: modules/erlang.md
        - F#: modules/fsharp.md
        - Go: modules/go.md
        - Haskell: modules/haskell.md
        - JavaScript: modules/js.md
        - LaTeX: modules/latex.md
        - Lua: modules/lua.md
        - OCaml: modules/ocaml.md
        - Perl: modules/perl.md
        - Python: modules/python.md
        - Racket: modules/racket.md
        - Ruby: modules/ruby.md
        - Rust: modules/rust.md
        - Scala: modules/scala.md
        - Scheme: modules/scheme.md
        - SCSS: modules/scss.md
        - Shell: modules/shell.md
        - TypeScript: modules/ts.md
        - Web/HTML: modules/web.md
        - XML: modules/xml.md
        - YAML: modules/yaml.md
    - Completion Frameworks:
        - Helm: modules/helm.md
        - Ido: modules/ido.md
        - Ivy: modules/ivy.md
        - Vertico: modules/vertico.md
    - Other Modules:
        - ERC (IRC): modules/erc.md
        - Evil (Vim): modules/evil.md
        - Key Chord: modules/key_chord.md
        - Literate Programming: modules/literate-programming.md
        - Org Mode: modules/orgmode.md
- FAQ: faq.md
- Troubleshooting: troubleshooting.md
- Contributing: contributing.md
- Support: support.md
extra_css:
  - css/extra.css
markdown_extensions:
  - admonition
theme:
  name: material
