;; Ye Prelude Modules.

(require 'prelude-clojure)
(require 'prelude-coffee)
(require 'prelude-company)
(require 'prelude-css)
(require 'prelude-emacs-lisp)
(require 'prelude-erc)
(require 'prelude-evil)
(require 'prelude-go)
(require 'prelude-helm)
(require 'prelude-helm-everywhere)
(require 'prelude-js)
(require 'prelude-latex)
(require 'prelude-lisp)
(require 'prelude-org)
(require 'prelude-perl)
(require 'prelude-python)
(require 'prelude-ruby)
(require 'prelude-scala)
(require 'prelude-scss)
(require 'prelude-web)
(require 'prelude-xml)
(require 'prelude-yaml)
